sudo: required
language: python
python:
  - "3.6"

services:
- docker

script:
- "./bin/lint"
- "./bin/test"

deploy:
  provider: pypi
  user: dev-im
  # This edge argument is intended to work around issue:
  # https://github.com/travis-ci/dpl/pull/834#issuecomment-434036325
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: "EfaHObFKrJ0Kodj0hbPS4k46IDcXaeXmxgM6anmRK2Zt6cqo/SWNVFE1YjnEvcb4X8uo8NKv+50aF5ETiqksUACO07QTkpKM1x5PtH37T9CP8K9SvffjZmNprTSKJ2eAq7Ay8+YUk5CFJc4sHBd3LiuV+mZk95/DHjuQps5OqslrZSfewd37XxzUYE/OFvBK7gLcIoZ6X7tLC+a+IYe1Ce2XxRAKTH0Vtd/pFlgKIHJ5tP52Zl/mSU5FMJVK/RVjQLHhbdVgckaiQbB8Ic01JfyIfbNeioOB+D1bcSC6LMp8bJRliC0mwtQV1nN7XS1cy7lLT/RHJJGEx3uBG98BqtpsABbR3Q789rv6fQH8rmi+ExPEERiTxZE+d4Ht42SfcLB96iXIrNMo1EGGpuVEc8MiPVMx3hBMhR2lMo4oavHaCFxsfv8shhTiqHdJ7zAJe+4oPmCTCEBebVnL+2xJQhJOVLF/OTEUDmIRha41nbxUHdl4zdtGKOrKNwXR19HoZIM7lN/K9+dySPqB4i25ksHEBS8u1CUemLWh1VeQqZH3cFPI2OxTcwF/OER+VNR/PHo5Nu3m8KtvYjt9dsuUAum08vWcUBmIdvPOzI81N11D2J2xuA0Yua4knj3DviV9TAwM+cSwxm+5toM6RdWEQhkt0gLSCPHitVWu4HoSqyo="
  on:
    tags: true

notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
